### ISSUE TITLE
Engine 'uglify' not found. Refusing to store configuration

### ISSUE THREAD

**Issue by brendo** [nknapp/bootprint-base#1]
Since the `0.8.0` release, I now receive an error when running Bootprint.

```
Engine 'uglify' not found. Refusing to store configuration
```

**Comment by brendo** [comment]
Right, so updating `bootprint` to `0.10.0` caused this problem to go away.

I noticed this module relies on `bootprint-base`, should it also rely on `bootprint`? Or should the uglify change be moved from `bootprint` to `bootprint-base`?

**Comment by nknapp** [comment]
Bootprint is a peer dependency of bootprint-base. The idea of the separation is that bootprint-base et.al. contains the template and bootprint contains the processing logic.

Since this is technically still initial development, the peer-dependency goes to version <1.0.0 
My plan is to do another such change today an then release bootprint@1.0.0, which should be the  last major change for a while.

I'm sorry for the inconvenience this caused. I have no good channel for announcing such changes yet.

Am 19. Dezember 2016 00:40:43 MEZ, schrieb Brendan Abbott <notifications@github.com>:
>Right, so updating `bootprint` to `0.10.0` caused this problem to go
>away.
>
>I noticed this module relies on `bootprint-base`, should it also rely
>on `bootprint`? Or should the uglify change be moved from `bootprint`
>to `bootprint-base`?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bootprint/bootprint-base/issues/1#issuecomment-267855889

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by brendo** [comment]
Ah gotcha! Sorry for the alarm!
